exchange:
  size: 10Gi
  storageClassName: standard

# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml
jupyterhub:
  debug:
    enabled: true

  proxy:
    service:
      type: NodePort
      nodePorts:
        http: 30080
    chp:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      extraPodSpec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

      networkPolicy:
        enabled: false

  rbac:
    create: true

  hub:
    extraFiles:
      # Files in /usr/local/etc/jupyterhub/jupyterhub_config.d are
      # automatically loaded in alphabetical order of the final file
      # name when JupyterHub starts.
      courses_management:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/00_config.py
      settings:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/01_config.py
      accessible_services:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/02_config.py
      courses_info_json:
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/courses_info.json

    config:
      Authenticator:
        # If any more admins, existing ones must set as admin in UI
        # Changes will disappear if db disappears
        admin_users:
          - 'polina.chubenko'
          - 'admin'
        allow_all: true
      DummyAuthenticator:
        password: qwerty
      JupyterHub:
        authenticator_class: dummy
    #   GitLabOAuthenticator:
    #     client_id: "35189e308948d4f04c3f68864bea0c97fb5d7d7bc49753c00f7c0f77b0c05527"
    #     client_secret: "gloas-d3e711de9c6b9ee2e79e633b17b8951df32ee3317aab3bc3dc651e16d9fe648e"
    #     oauth_callback_url: "https://jupyterhub.sunpixel.ru/hub/oauth_callback"
    #     scope:
    #       - read_user
    #       - read_api
    #       - openid
    #   JupyterHub:
    #     authenticator_class: gitlab
    extraEnv:
      # GITLAB_HOST: "gitlab.akhcheck.ru"
      MANAGER_TOKEN:
        valueFrom:
          secretKeyRef:
            name: manager-token-secret
            key: token
    image:
      name: nbgrader-hub-sample
      tag: 0.0.1
    # resources:
    #   requests:
    #     memory: '2Gi'
    #     cpu: '2000m'
    #   limits:
    #     memory: '2Gi'
    #     cpu: '2000m'
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 10
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 10
      timeoutSeconds: 10
    db:
      pvc:
        storageClassName: 'standard'
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    consecutiveFailureLimit: 0
    networkPolicy:
      enabled: false
      interNamespaceAccessLabels: 'accept'
      egressAllowRules:
        cloudMetadataServer: false
    # Exchange dir mounted to hub pod to ensure student path creation
    extraVolumes:
      - name: nbgrader-exchange
        persistentVolumeClaim:
          claimName: nbgrader-exchange
      - name: nbgrader-config-global
        configMap:
          name: nbgrader-config-global
    extraVolumeMounts:
      - name: nbgrader-exchange
        mountPath: '/mnt/exchange'
      - name: nbgrader-config-global
        mountPath: '/etc/jupyter/'
        readOnly: true

  singleuser:
    # cpu:
    #   limit: .5
    #   guarantee: .5
    # memory:
    #   limit: 2G
    #   guarantee: 500M
    networkPolicy:
      enabled: false
    cloudMetadata:
      blockWithIptables: false
    defaultUrl: '/lab'
    storage:
      type: none
      extraVolumes:
        - name: nbgrader-config-global
          configMap:
            name: nbgrader-config-global
      extraVolumeMounts:
        - name: nbgrader-config-global
          mountPath: '/etc/jupyter/'
          readOnly: true
    cmd: jupyterhub-singleuser
    uid: 1000
    fsGid: 100
    startTimeout: 300
    allowPrivilegeEscalation: false
    extraPodConfig:
      securityContext:
        fsGroup: 100
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

  scheduling:
    userScheduler:
      enabled: false
    userPlaceholder:
      enabled: false

  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false

  cull:
    enabled: false
    users: true
    timeout: 259200
    every: 3600
